#!/bin/bash

# Define the input and output file paths
INPUT_FILE="./AMZN_data_1999_2022.csv"
OUTPUT_FILE="out/amazon_date_close.csv"

# Extract the 'Date', 'Close', and 'Volume' columns and save them to a new file
awk -F, 'BEGIN {OFS=","} {print $1, $5, $7}' $INPUT_FILE > $OUTPUT_FILE

